# VERSION 1.0
# AUTHOR: Tyler Chun
# DESCRIPTION: NGINX on Ubuntu 18.04
# SOURCE: https://github.com/nethacker/ubuntu-flask-gunicorn-nginx-docker-compose
FROM nginx:1.23.1
COPY nginx.conf /etc/nginx/conf.d/default.conf
